#!/usr/bin/env python3
"""Design/verify CMX918 FIR2 tables. Requires NumPy and SciPy; no hardware I/O.

DS D/918/2.0 pp.20–23: symmetric 80 taps, mirrored half at D7=16..55,
strict coefficient limits 4096/16384, unity DC sum 65536. Frequencies below
are relative to the FIR2 processing clock, inferred as 4.8*profile bandwidth
from Figure 10/Table 6, independent of the final x2 output-rate divider.
These are FIR-only responses, not a model of CIC/analogue stages.
"""
import argparse
import json
from pathlib import Path

import numpy as np
import scipy
from scipy.signal import freqz, remez

ROOT = Path(__file__).resolve().parents[1]
DESIGNS = [
    ("HALF", .225, .25, .8, 50),
    ("FULL", .45, .49, .15, 65),
    ("QUARTER", .105, .125, 1.6, 43),
]


def design():
    text = "// Generated by scripts/design_wide_fir.py; see docs/WIDE-FIR.md.\n"
    report = {"numpy": np.__version__, "scipy": scipy.__version__, "filters": {}}
    for name, passed, stopped, ripple_limit, rejection_limit in DESIGNS:
        h = remez(80, [0, passed, stopped, .5], [1, 0],
                  weight=[1, 20], fs=1, maxiter=200)
        limits = np.r_[np.full(20, 4095), np.full(20, 16383)]
        scale = min(1., np.min(limits / np.maximum(abs(h[:40]), 1e-30) / 65536)) * .98
        q = np.rint(h[:40] * scale * 65536).astype(int)
        full = np.r_[q, q[::-1]] / 65536
        f, response = freqz(full, worN=65536, fs=1)
        dc = sum(full)
        db = 20 * np.log10(np.maximum(abs(response) / dc, 1e-15))
        passed_db = db[f <= passed]
        rejection = -max(db[f >= stopped])
        assert np.all(abs(q) <= limits)
        assert np.max(abs(passed_db)) < ripple_limit
        assert rejection > rejection_limit
        # An even symmetric FIR necessarily has a Nyquist zero.
        assert abs(np.dot(full, (-1.) ** np.arange(80))) < 1e-12
        text += f"pub const {name}: [i16; 40] = [\n"
        for row in q.reshape(5, 8):
            text += "    " + ", ".join(map(str, row)) + ",\n"
        text += "];\n"
        report["filters"][name] = dict(pass_edge=passed, stop_edge=stopped,
            dc_gain_db=float(20*np.log10(dc)),
            pass_min_db=float(min(passed_db)), pass_max_db=float(max(passed_db)),
            stop_rejection_db=float(rejection), half_sum=int(sum(q)))
    return text, report


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--report", type=Path)
    args = parser.parse_args()
    text, report = design()
    target = ROOT / "firmware/src/wide_fir_tables.rs"
    if args.check:
        # Ignore rustfmt layout; exact signed integer tables must agree.
        import re
        integers = lambda t: re.findall(r"-?\d+", t)
        assert integers(target.read_text()) == integers(text), "Generated FIR table is stale"
    else:
        target.write_text(text)
    if args.report:
        args.report.parent.mkdir(parents=True, exist_ok=True)
        args.report.write_text(json.dumps(report, indent=2) + "\n")
    print(json.dumps(report, indent=2))


if __name__ == "__main__":
    main()
